[package]
name = "edgeframe"
version = "0.2.0"
entrypoint = "lib.typ"
authors = ["neuralpain <https://github.com/neuralpain>"]
license = "MIT"
description = "For quick paper setups."
repository = "https://github.com/neuralpain/edgeframe"
keywords = ["edgeframe", "margin", "word"]
categories = ["office", "layout"]
